### ISSUE TITLE
Database Solution

### ISSUE THREAD

**Issue by carlosadean** [linea-it/idac_br#6]
```[tasklist]
### Tasks - pre-installation
- [ ] https://github.com/linea-it/idac_db/issues/2
- [x] 1- Validar se o rack suporta peso do servidor com 88kg + componentes (46,5Kg)
- [x] 2- Validar se o piso suporta o peso do rack completo preenchido.
- [x] 3- PDU de conexão do rack vizinho + validar se a potência é suficiente. (solicitar fotos ao cliente)
- [x] 4- Cabos de força c13 e c14 de 5m (cliente vai comprar) - 15Am pode ser utilizado e posteriormente trocar por de 20Am.
- [x] 5- Cabos de rede CAT6 ou CAT6A (RJ45) - 4 e 5mts
- [x] 6- Cabos HDR não será necessária á compra.
- [x] 7- Solicitar fotos da bayface do rack (frente, trás, ambiente)
- [x] 8- Cliente irá alinhar com timbira config do servidor de banco de dados. (lista de sistemas operacionais homologados)
- [x] 9- Profundidade do servidor é de 107cm - o servidor precisa ser instalado em rack de profundidade mínima de 120cm
- [x] 10- Endereço MAC - Cliente irá verificar se é necessário
- [x] Solicitar acesso ao datacenter do LNCC para a semana 14-18/Out
- [x] Solicitar acesso ao wifi do LNCC
- [x] Arrumar cabos EDR no rack para encaixar o servidor (4U)
- [x] Designar endereço IPv4 do sistema
```

```[tasklist]
### Tasks - Documentação da solução
- [x] Diagrama físico da rede ethernet
- [x] Diagrama físico da rede infiniband
- [ ] Diagrama dos cabos de energia
- [x] Diagrama das configurações lógicas de rede
- [x] Diagrama do rack
```
